py/src/braintrust/cli/__main__.py, py/src/braintrust/cli/install/__init__.py
After this change, `braintrust eval` won't require `pip install braintrust[cli]`
=> Only require cli extra for the `install` functionality

js/src/logger.ts, py/src/braintrust/logger.py
Since the logger writes batches of records to the API, we need to ensure we do not send more than the 10 MB limit of API gateway. This change simply predicts the batch length by serializing JSON values before sending them off.
There is a more efficient version of this change that does a streaming serialization of JSON values (and concatenates them together with `,`), but I think we can explore that later if needed.
=> Ensure we do not log more than the maximum API gateway can handle

py/src/braintrust/logger.py
This allows the catch-all warning we send to still send a single instruction (call `.close()`)
=> Add a .close() method as an alias for .end() for spans

py/src/braintrust/gitutil.py, py/src/braintrust/logger.py
After this change, if `git` is missing, we still import the `git` package but (as expected) do not use git metadata.
Also fixed the token logic to only run if we're in a terminal.
=> Do not loudly fail if git is missing

js/src/logger.ts, py/src/braintrust/logger.py
Tested locally by failing the `logs` endpoint in chalice.
Fixes BRA-515
=> Logger: warn instead of crashing when logging fails. Also attempt retry.

js/src/logger.ts, js/src/merge_row_batch.ts, js/src/util.ts, py/src/braintrust/logger.py
As long as the row IDs in a set of rows are independent, we can batch them up and log them concurrently. The only extra step we need then is to merge rows with the same ID before logging, which saves on bandwidth anyways.
Aside from sanity-check testing, verified on prod that the `stress-tests/large_experiment.ts` benchmark, run with 1 experiment of 5000 rows shows improvement. Before, it took about 321.26 seconds. After it takes about 99.77 seconds.
=> JS SDK: Launch logging requests concurrently.

js/src/logger.ts, py/src/braintrust/cli/install/logs.py, py/src/braintrust/logger.py
Our empirical testing shows the limit is around 6MB. This aligns with the internal server errors customers were seeing
=> Adjust sdk logging limit.

js/package-lock.json, js/package.json, js/src/isomorph.ts, js/src/logger.ts, js/src/node.ts
Switch to using (isomorphic) fetch. This requires node >= 17, but we haven't tested on earlier versions (and doubt we support them).
With this change, the SDK should work just fine in edge runtimes (https://github.com/axios/axios/issues/5523)
=> Remove axios

js/src/isomorph.ts, js/src/logger.ts, js/src/node.ts, py/src/braintrust/logger.py
Python:
- `braintrust.start_span` should have an optional name, as in the JS
version.
Javascript:
- Mirror the atexit flushing in the python SDK in JS.
=> Minor tweaks to SDKs

js/src/cli.ts, js/src/framework.ts, js/src/index.ts, py/src/braintrust/cli/eval.py, py/src/braintrust/framework.py, py/src/braintrust/logger.py
Sometimes it's useful to specify additional metadata for the experiment, such as the name of the experiment. We also add support for running multiple evals with the same project and different experiment names.
=> Add metadata field to eval definition.

js/src/logger.ts, py/src/braintrust/logger.py
This can be useful for local testing, if we want to mix and match which API endpoint and which chalice deployment we are using.
=> Allow overriding log url in SDK.

js/src/index.ts, py/src/braintrust/logger.py
The condition variable approach was flawed because `condition_variable.wait()` will only respond to notify signals sent after the `wait` runs. So if the logger thread was in the middle of a flush while the producer thread fills up the queue and sends a notify signal, the consumer thread will miss the notify signal on its next `wait` call and we have a deadlock.
The solution is to replace the condition variable with a semaphore. So that the producer can increment the semaphore as a "persistent" way to trigger the consumer thread, which blocks on the semaphore being 0.
One possible concern is that the background thread can spin for a while on a filled-up semaphore after draining the queue (since we call `release` each time we log). I ran a quick benchmark for the cost to drain a semaphore: …
=> Fix deadlock in python logger.

py/setup.py
To fix the pip warning
```
WARNING: pydoc-markdown 4.8.2 does not provide the extra 'novella'
```
It doesn't look like we use novella anyways.
=> Update pydoc-markdown requirement

js/src/gitutil.ts, py/src/braintrust/gitutil.py
`get_past_n_ancestors` would crash in python if `git merge-base` was failing. Also made the TS and PY implementations more aligned.
=> SDK fixes for github actions.

py/src/braintrust/gitutil.py
Was seeing errors like the following in CI tests.
```
File "/home/runner/work/braintrust/braintrust/sdk/py/src/braintrust/gitutil.py", line 101, in get_past_n_ancestors
if ancestor.parents:
^^^^^^^^^^^^^^^^
File "/home/runner/work/braintrust/braintrust/venv/lib/python3.11/site-packages/gitdb/util.py", line 253, in __getattr__
self._set_cache_(attr)
File "/home/runner/work/braintrust/braintrust/venv/lib/python3.11/site-packages/git/objects/commit.py", line 215, in _set_cache_
_binsha, _typename, self.size, stream = self.repo.odb.stream(self.binsha)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/runner/work/braintrust/braintrust/venv/lib/python3.11/site-packages/git/db.py", line 45, in stream
hexsha, typename, size, stream = self._git.stream_object_data(bin_to_hex(binsha)) …
```
=> Fix gitutil crash when repo is partially downloaded.

js/src/cli.ts, py/src/braintrust/cli/__main__.py, py/src/braintrust/cli/eval.py
- The `braintrust eval` python command can emulate the `python -m unittest` command by adding the directory python was invoked in to `sys.path`. This lets eval files that are run through the CLI to import other paths in the project.
- Add a `--terminate-on-failure` option to both PY and JS eval commands, which terminates the eval runner upon any eval file that itself crashes. This lets us properly propagate crashes out of the eval runner, which we can pick up in our own unit tests.
=> A couple testing-related improvements

js/src/browser-config.ts, js/src/browser.ts, js/src/logger.ts, js/src/oai.ts
There were two issues here:
* We weren't exporting `oai.ts` from the `browser.ts` entrypoint, which next.js's edge runtime uses
* Next.js seems to stub / support `AsyncLocalStorage` in edge environments, even though it's not supported in the browser. I copied a small snippet of code that adds it to global scope and attempt to initialize it, which fixes it in edge environments.
=> Fix OpenAI wrapping in edge environments

js/src/logger.ts, py/src/braintrust/logger.py
It's useful to be able to specify base experiments (by name) before they exist, e.g. in a CI system where you know what they'll be called but they may run out of order. This changes the SDK to mark them as a warning (and retry registration) if the base experiment does not exist.
=> Issue a warning, not an error, if an invalid base experiment is specified

js/src/gitutil.ts, py/src/braintrust/gitutil.py
I'm working on a few experiment metadata related changes, and want to improve the UX when you're running in a dirty repo to still capture the git metadata.
=> Still capture git metadata, even if dirty

js/src/index.ts, py/src/braintrust/__init__.py, py/src/braintrust/logger.py
We had mistakenly updated the documentation `.md` files instead of the SDK code itself.
=> Update docs in code itself.

js/src/logger.ts, py/src/braintrust/logger.py
Enable metric summaries (like duration) from the new `experiment-comparison2` endpoint.
=> Support metric summaries

js/src/framework.ts, py/src/braintrust/framework.py
Users were reporting that the `--verbose` flag is lost if it's at the beginning of the list of errors. This change simply prints the clarification at the end (and adds it to python)
=> Show --verbose warning at the end of the error list

js/src/framework.ts, js/src/index.ts, py/src/braintrust/__init__.py
* Change built-in examples to use Eval framework
* Use `evaluator` instead of `_evals[evalName]` to access metadata. The latter is not set if you're running Evals directly in a script.
=> Small fixes

core/js/src/score.ts, js/src/framework.ts
Fixes BRA-692.
Tested locally by verifying that the compiler doesn't complain when I try to create an invocation of the scorer with additional arguments, e.g. `(args) => Factuality({...args, model: "gpt-4"})`.
=> Fix type signatures for scorers in eval framework.

js/src/logger.ts
Deno doesn't support the `enterWith` function in `AsyncLocalStorage`:
- https://github.com/denoland/deno/issues/18127
The function is still marked experimental.
- https://nodejs.org/api/async_context.html#asynclocalstorageenterwithstore
This PR checks the `enterWith` function exists before calling it.
=> Check if AsyncLocalStorage has enterWith function, to make Deno happy

js/src/oai.ts
This seems to work, but probably needs more testing.
This change adds support for `wrapOpenAI` to also trace `openai.beta.chat.completions.stream` calls:
https://github.com/openai/openai-node?tab=readme-ov-file#streaming-responses-1
=> Add support in wrapOpenAI for the beta.chat.completions.stream API

.pre-commit-config.yaml, js/package.json, js/src/logger.ts, package.json, pnpm-lock.yaml, pnpm-workspace.yaml, turbo.json
Now that we have multiple JS packages in the same repo which depend on each other, it is useful to manage them with turborepo. We already do this in other repos, such as
https://github.com/braintrustdata/braintrust-proxy.
=> Manage repo as pnpm workspace

py/src/braintrust/cli/eval.py, py/src/braintrust/cli/install/redshift.py, py/src/braintrust/framework.py, py/src/braintrust/logger.py, py/src/braintrust/util.py
Subset of https://github.com/braintrustdata/braintrust-sdk/pull/67 which addresses only the python part. This will let us work on the JS changes independently.
It is basically the python-changes up to https://github.com/braintrustdata/braintrust-sdk/pull/67/commits/8840d35937752f36150e5673827bffb2be70d930, with the comments addressed.
=> Simplify python tracing API

py/src/braintrust/framework.py, py/src/braintrust/logger.py
Motivation was for the Eval framework to not leave the global experiment lying around afterwards for people to accidentally write to.
=> Add option to not set new experiment/logger as current.

js/src/browser-config.ts
In some environments, AsyncLocalStorage is just not defined (eg convex.dev), so check before trying to initialize it.
=> Check if async local storage defined

js/src/cli.ts, js/src/framework.ts, js/src/logger.ts
Analogue to https://github.com/braintrustdata/braintrust-sdk/pull/74.
This is a carry-over from
https://github.com/braintrustdata/braintrust-sdk/pull/67, with the JS comments addressed.
=> Simplify JS tracing API

js/src/logger.ts, py/src/braintrust/logger.py
We introduced logic in
https://github.com/braintrustdata/braintrust-sdk/pull/4 to infer `force_login=True` if the login params you provide are different from what we have currently logged in as.
But this logic ended up creating a bug in the eval framework, where if you login initially with custom params here
(https://github.com/braintrustdata/braintrust-sdk/blob/844d83b7df2de4b09dd03176391964fa25cae046/py/src/braintrust/cli/eval.py#L202), then we would try to login again whenever creating an experiment here (https://github.com/braintrustdata/braintrust-sdk/blob/844d83b7df2de4b09dd03176391964fa25cae046/py/src/braintrust/framework.py#L396), and the second login could trigger a `force_login` because it uses whatever is in the environment variables.
While there are other ways to work around …
=> Undo infer `force_login`.

js/src/gitutil.ts
**GitUtil: Add try-catch block when resolving Git repo**
* Added simple try-catch around `simpleGit()` initialization - If anything error'ed out, `null` will be returned.
=> GitUtil: Add try-catch block when resolving Git repo

py/src/braintrust/gitutil.py
* Make `attempt` also catch `ValueError`, which is raised when calling `repo.head.commit` in an empty git repo
* Also move all `.strip()`s inside the lambdas otherwise `None.strip()` errors
Fixes BRA-730
=> Fix handling of empty git repo and other git errors

js/src/gitutil.ts, py/src/braintrust/gitutil.py
We can revisit truncating big diffs for individual files in a smarter way later.
Fixes BRA-767
=> Truncate large git diffs to max 64 KB

core/js/src/git_fields.ts, core/js/src/index.ts, core/py/src/braintrust_core/__init__.py, core/py/src/braintrust_core/git_fields.py, js/src/gitutil.ts, js/src/isomorph.ts, js/src/logger.ts, py/src/braintrust/gitutil.py, py/src/braintrust/logger.py
Now that we support configuring which git metadata you can collect at an org-wide level, this change updates the SDK to respect that configuration, and further allows users to optionally override it (merging the two settings into the _least_ permissive setting).
=> Only send git metadata that's configured as allowed

js/src/gitutil.ts, js/src/logger.ts, js/src/util.ts, py/src/braintrust/gitutil.py
To accomplish lazy initialization, we were wrapping everything in promises. The problem with this is that if the promise is not awaited (more specifically, a rejection handler is not explicitly attached), the promise's exceptions will get reported as "unhandled" at the end of the program, as it's clearing out its event loop. This seems to happen even if the promise is awaited somewhere else and the exception handled (i.e. in the background logger). I think as long as there is still some context in which the promise may run without a rejection handler, it will bubble up at the end.
To work around this, we add one more step of indirection, now similar to what we do in the python SDK. The LazyValue wrapper creates the promise only when asked for, and the user is expected to await it …
=> Fix unhandled promise rejections in typescript SDK.

py/src/braintrust/oai.py
We redefined this, incorrectly. I noticed this while debugging an autoevals failure
=> Fix sync embedding wrapper

js/src/logger.ts, py/src/braintrust/logger.py
This change introduces a global counter that we track, in addition to start time, to help tie breaks spans. This is useful if two spans start in a logical order, within the same millisecond, so that they'll appear in the same order in the UI across traces.
=> Track execution counter

py/src/braintrust/logger.py
Similar to what we do in javascript. This way any issues encountered during logging will not crash the application.
Fixes BRA-550
=> Python SDK: print exceptions instead of aborting logger

js/src/oai.ts, py/src/braintrust/oai.py
Just remove the vector and replace it with `{"embedding_length": <length>}` for now. We can add a flag for it later if it turns out to be useful.
=> Don't log full embedding vector from EmbeddingWrapper

core/py/src/braintrust_core/util.py, py/src/braintrust/cli/eval.py, py/src/braintrust/framework.py, py/src/braintrust/logger.py, py/src/braintrust/util.py
It's useful in other places too (e.g. chalicelib).
=> Move `eprint` to core.

js/src/logger.ts, py/src/braintrust/logger.py
Before it would "replace" the existing experiment, which means overwriting any specified metadata on the existing experiment, or creating a new one. But we think the more useful purpose is to re-open an existing experiment in read-write mode.
=> Modify `update` in experiment init to just open the experiment.

py/src/braintrust/logger.py
This was only introduce in
https://github.com/braintrustdata/braintrust-sdk/pull/113, so I don't think it's made it to any users.
=> Fix bug in setting repo info when creating experiment.

js/src/logger.ts, py/src/braintrust/logger.py
Basically re-introducing the logic in
https://github.com/braintrustdata/braintrust-sdk/pull/4 (reverted in https://github.com/braintrustdata/braintrust-sdk/pull/82), but only if the arguments are explicitly provided. So implicit environment variable settings which differ from the existing logic will continue to silently not login.
=> Raise exception when trying to re-log in with explicitly different params.

core/js/src/typespecs/api_types.ts, core/js/src/typespecs/common_types.ts, core/py/src/braintrust_core/util.py, py/src/braintrust/logger.py, py/src/braintrust/util.py
This should give us parity with the endpoints used by the SDKs, which means we can start replacing the SDK endpoints with these once users have upgraded their backend.
=> Typespecs: Add summarization and cross-object insertion endpoints

js/src/framework.ts, py/src/braintrust/framework.py
We automatically de-duplicate the experiment name when creating it, so enforcing uniqueness is unnecessary.
=> Eval framework allow duplicate names

core/py/src/braintrust_core/bt_json.py
Using `super().default(o)` did not work for us as we have some types that are not serializable out of the box, i.e our pydantic models have other model types as attributes:
```
class KYBProofOfAddressVerificationTool(BaseCheckTool):
tool_id: ClassVar[str] = "kyb.proof_of_address_verification"
name: str = "Proof of Address Verification Tool"
description: str = "A tool to verify a proof of address document provided by applicant and extracting relevant data"
args_schema: Type[BaseCheckArgsSchema] = ProofOfAddressVerificationArgsSchema
output_payload_schema: Type[BaseOutputSchema] = ProofOfAddressCheckResult
input_data_schema: Type[ProofOfAddressCheckInputs] = ProofOfAddressCheckInputs
verification_data_schema: Type[ProofOfAddressExtractonData] = ProofOfAddressExtractonData
```
The proposed …
=> Fallback to str(o)

js/src/framework.ts, js/src/logger.ts, py/src/braintrust/framework.py, py/src/braintrust/logger.py
It was pointed out that objects logged to braintrust may be mutated after logging, and braintrust would end up logging the mutated version. We fix this by round-tripping the object through the JSON serializer, which doubles as a synchronous check for serializability (that we were already doing in python).
We also adjust the `@traced` decorator in python to log the input before running the function, so that it's immediately visible.
=> Log objects eagerly

js/src/util.ts
Since the `.get` method was async, it was possible that multiple callers could invoke it concurrently. Also it was awaiting the result of the callable in the same statement as setting the callable to computed, which allows multiple callers to generate and await the callable concurrently.
The observed result is that the LazyValue function could be invoked multiple times, and we might end up registering multiple experiments. The new implementation should guarantee we invoke the callable at most once.
=> Fix bug in JS LazyValue

js/src/oai.ts
The stream object in the openAI api has some other functionality other than just being an `AsyncIterator` (e.g. `toReadableStream`, `tee`, etc.). So just wrap the iterator itself and return the base open ai stream object
Not sure if this is what you were looking for but it seems to work.
=> wrap the iterator only in the OAI stream interface

py/src/braintrust/logger.py
Store it as a class variable on the connection, and set it explicitly.
=> Do not lose adapter on reset

js/src/framework.ts, js/src/logger.ts
This way if it's unspecified, you won't see a compiler error
=> Default Expected to void

py/src/braintrust/logger.py
Noticed it's really starting to spam the unit tests. Seems mainly useful for debugging anyways.
=> Demote "flushing final log events" message from info to debug.

core/js/typespecs/api_types.ts, core/js/typespecs/app_types.ts, core/js/typespecs/openai/messages.ts, core/js/typespecs/openai/tools.ts, core/js/typespecs/prompt.ts
Replaced all instances of `z.object` with `z.strictObject`, which seems like a less error-prone way to ensure strictness everywhere by default.
=> Typespecs: more strictness

js/src/framework.ts, py/src/braintrust/framework.py
Non-objects (nulls and numbers) are not particularly usable, since we don't know what name to attach to each score. This change forces each returned value to be an object, and returns a runtime error if not (along w/ a type error if you're using typescript).
=> Constrain score lists to be objects

core/js/typespecs/prompt.ts
After https://github.com/braintrustdata/braintrust-sdk/pull/166, we moved to using strict objects by default. Apparently creating intersections between two strict objects (e.g.
`braintrustModelParamsSchema` and `openAIModelParamsSchema`) doesn't seem to work at all. We have to use `merge` to make everything work.
See https://github.com/colinhacks/zod/issues/390 for an explanation of the issue.
=> Fix prompt params typespecs.

js/src/logger.ts, py/src/braintrust/logger.py
We are seeing this error more broadly than just calling `experiment.log` within an active span. Generally we think most users don't want to mix traced and non-traced logging in the same object ever, so we broaden the check to fire if it ever happens.
=> Broaden toplevel `log` error to having called `traced` anywhere.

core/py/src/braintrust_core/span_parent_identifier.py, js/src/logger.ts, py/src/braintrust/logger.py
- Use Enum instead of StrEnum due to lack of availability in older pythons
- Add `export` to `NoopSpan` (and thus allow returning None/undefined from the method).
=> Small cleanups to span parent id functionality

js/src/logger.ts, js/src/oai.ts, py/src/braintrust/oai.py
In general allow passing any of the params that could be used to create a span. Type-wise, we just include `name` and `span_attributes` in the TS type signatures, but could add anything else in `StartSpanArgs` if needed.
=> Generalize span_info args for oai wrappers.

js/src/logger.ts, py/src/braintrust/__init__.py, py/src/braintrust/logger.py
Originally we would spawn a separate BackgroundLogger for each object we created. This is not particularly useful anymore, because the background logger already batches and parallelizes requests. It also leads to problems with flushing, because you have to call flush on every logger that you have logged to (including the global logger if you are doing distributed tracing).
We change everything to use just the single global logger and add a global flush function for good measure. Fix a few bugs along the way.
=> Use single global BackgroundLogger instance everywhere.

js/src/logger.ts, py/src/braintrust/logger.py
Also removed the fallback requests, because after
https://github.com/braintrustdata/braintrust-sdk/pull/159, we require API version 0.0.35, which includes the REST API.
Tested on prod by fetching a very large dataset successfully in the SDK. Verified that things fail without gzip compression by changing the header from `Accept-Encoding: gzip` to `Accept-Encoding: identity`.
=> Use REST API endpoints for fetching data.

py/src/braintrust/framework.py
We were errantly handling the `VAR_KEYWORD`, i.e. `kwargs` param and the `final_kwargs` argument would just include it as an arg named `kwargs`.
=> Fix kwargs param

core/py/src/braintrust_core/bt_json.py
This fails on the server-side, so catch it early in Python.
=> Explicitly disallow NaN while serializing

js/src/logger.ts, py/src/braintrust/logger.py
This was broken in both Py and JS, for slightly different reasons.
=> Fix tools in managed prompts

js/package.json, js/src/cli.ts, pnpm-lock.yaml, py/setup.py, py/src/braintrust/cli/eval.py
Follows the `.env.*` conventions laid out (and implemented) by Next.js.
For both TS and Py, add a `--env-file` flag to specify an env file
=> Incorporate .env files in CLI

js/src/logger.ts, py/src/braintrust/logger.py
`BRAINTRUST_ALL_PUBLISH_PAYLOADS_DIR`: Set this to log all payloads we publish (regardless of success or failure) to the specified directory.
`BRAINTRUST_QUEUE_DROP_WHEN_FULL` (in python): configures the logger to drop additional elements instead of doing a blocking insert.
`BRAINTRUST_QUEUE_DROP_EXCEEDING_MAXSIZE` (in javascript): configures the logger to drop elements after exceeding the given size. This is basically a combination of `BRAINTRUST_QUEUE_SIZE` and `BRAINTRUST_QUEUE_DROP_WHEN_FULL`. The reason we can't use the same params in JS is that JS doesn't have a blocking queue functionality.
Fixes BRA-1332, BRA-1215
=> Add some more tuning params to the loggers.

README.md, core/js/package.json, core/js/src/merge_row_batch.ts, core/js/typespecs/api_types.ts, core/py/setup.py, core/py/src/braintrust_core/merge_row_batch.py, js/src/cli.ts, js/src/logger.ts, py/setup.py, py/src/braintrust/cli/eval.py, py/src/braintrust/cli/install/api.py, py/src/braintrust/logger.py
Currently, our redirects are a bit of a mess, because we redirect braintrustdata.com->www.braintrust.dev, but cannot redirect www.braintrustdata.com because there are SDKs that reference that API (and were failing to point to braintrust.dev).
This change reworks everything to braintrust.dev.
=> Fix SDK to point to braintrust.dev

core/js/typespecs/app_types.ts
While implementing the RBAC UI internally, we discovered that the current PATCH API is prone to race-conditions, because adding/removing members of a group or role requires reading the full list and then replacing it with an updated list. We replace the replace-list params with separate add/remove-from-list params to fix this.
If people truly want to replace the lists, they can use a `PUT` request.
=> Robustify the `patch` endpoint for groups and roles.

py/src/braintrust/framework.py
Prior to this change, when you ran `Eval()` in a notebook, it'd spit out a full summary along with all the results. This just cleans up the `_repr_pretty_` implementation to print a tighter object.
Note that we print (to the console) the summary itself, so if we printed the summary itself, it'd show up twice.
=> Improve IPython repr for EvalResultWithSummary

js/src/browser-config.ts
Our isomorphic code should attempt to use environment variables, even in environments that are "browser-like" (i.e. non-node). Vercel edge functions/cloudflare, for example, set process.env.
=> Try to use env variables in browser environments

js/src/logger.ts
We noticed that Vercel edge functions appear to do the equivalent of `Accept: ""` which breaks our API handler code. This change explicitly sets the accept header, in the hopes that it will fix that issue.
=> Accept json content type explicitly

js/src/logger.ts
We saw a Sentry crash where a user somehow got a scores object into the database as an array. My theory is that this happened because the validation is too lose on this function. 
An input like `{scores: [0.5, 0.8, 0.9]}` will not trigger an exception as Object.entries happily turns that into ['0', 0.5], ['1', 0.8], ['2', 0.9], which looks like valid scores data.
Let's explicitly check for arrays and throw if users try to log scores that are arrays.
=> Explicitly check for arrays when logging scores

core/js/src/span_identifier.ts, core/py/src/braintrust_core/span_identifier.py, js/src/logger.ts, js/src/util.ts, py/src/braintrust/logger.py
Currently, logging is fully non-blocking (in that it doesn't need to hit the network on the critical path), except for the `[Logger/Span].export` function, which needs to resolve the object ID to serialize for the distributed tracer.
In order to work around this and make the export function non-blocking, we pass the arguments to the logger's `computeMetadata` registration function into the `Logger` and include them in the serialized span identifier if the object ID has not yet been resolved. Then when deserializing the parent span slug, we can obtain the object ID either from the serialized ID or by reconstructing the `computeMetadata` lambda from the serialized args.
=> Logger: don't block span export on resolving id

core/js/typespecs/app_types.ts
We are using it now and it doesn't seem necessary (and maybe a bit risky) to return the binary key hash.
=> Remove key_hash from api keys schema.

py/src/braintrust/cli/__main__.py, py/src/braintrust/framework.py
Currently, must be specified by the Eval function.
We could set a global timeout from the cmd line in the future.
=> fix(sdk-py): add timeout parameter to Eval

py/src/braintrust/framework.py
timeout was not introduced until Python 3.11.
=> fix(sdk-py): use asyncio.wait_for instead of timeout

core/js/src/span_identifier_v2.ts, core/py/src/braintrust_core/span_identifier_v2.py
`auto()` in python [starts from 1](https://docs.python.org/3/library/enum.html), not `0`. But we incremented the equivalent components from 0 in JS.
=> Make object type consistent across JS and Py for distributed tracing

js/src/logger.ts
If the span components are serialized in, e.g. Python, they may have `null` instead of `undefined` for the object ids.
=> Fix distributed tracing object id checks in JS

js/src/wrappers/ai-sdk.ts, js/src/wrappers/oai.ts, py/src/braintrust/logger.py
* `py.typed` instructs mypy that it can use the types in `braintrust` to do type checking
* The overloaded case helps mypy realize that calls to `@traced` without additional arguments can simply propagate the original type of `F`.
=> Add py.typed and fix type signature for @traced

py/src/braintrust/cli/__main__.py
This removes the
```
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/resource_tracker.py:254: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
warnings.warn('resource_tracker: There appear to be %d '
```
error
=> Shut down gracefully under normal circumstances

core/js/typespecs/openai/messages.ts, core/js/typespecs/prompt.ts, js/src/logger.ts
This is likely not the final solution... but allow the messages array to have a fallback for arbitrary roles (e.g. "model" from google), so that in the playground, we permit non-openai-compatible sessions.
`prompt.build()` still needs to produce something that typechecks with the OpenAI API, so still expose `OpenAIMessages` and cast `prompt.build()` to that. Note that with this approach, you can (incorrectly) cast a Google prompt to OpenAI.
=> Add a prompt fallback

core/js/typespecs/prompt.ts
* Add `window.ai` model params
* Use `passthrough` parsing in the union, so that if a set of model params gets accidentally identified in the wrong branch of a union, it does not strip the parameters. We were, for example, stripping the top k parameter.
=> Allow window.ai model params and fix a bug

js/src/cli.ts
I don't know why (and git doesn't seem to tell more) why we did a catch-all filter here, but it breaks some complex bundling scenarios (exposed in a test app we're working on). The intent was to exclude braintrust-flavored packages, so I made the regex more specific and manually confirmed.
=> Only mark braintrust/autoevals as external

js/src/logger.ts
This change allows you to propagate your own `fetch` to the SDK.
=> Add support for custom fetch

js/src/logger.ts
This allows systems that intercept the header to do so for the api key login as well.
=> Use header for api key login

core/js/typespecs/api_types.ts
This lets us specify a `created` timestamp when using the REST API, which is useful at least for unit testing and doesn't seem too harmful to expose to the public.
=> Add created timestamp to insert event schemas.

core/js/typespecs/api_types.ts, core/js/typespecs/app_types.ts
The schema exports used for API spec generation omit a lot of members that we don't actually want to define methods for (e.g. `organization.delete`, or anything related to `prompt_session`, or object summarization). Instead of explicitly writing in `undefined` for each method of each object type, we allow specifying undefined for each method, but require some entry for each object type. This way, you don't forget to add a new object type to the exports object.
Making fields optional requires erasing some type information for individual schemas. This is fine for the API spec generator, which doesn't care about exact types. But it does impact some internal code which is grabbing typedefs from `objectSchemas` or `eventObjectSchemas` directly. Instead, that code will import the typespecs they …
=> De-verbosify schema definitions.

js/src/logger.ts
This wrapper resembles the `@braintrust.traced` decorator in Python.
=> Add trace wrapper

core/js/typespecs/view.ts
This will make it easier to add new fields to the view schema without breaking compatibility.
=> Use .strip() for views fields

core/js/src/index.ts, core/js/src/util.test.ts, core/js/src/util.ts, core/js/src/zod_util.test.ts, core/js/src/zod_util.ts, core/js/typespecs/api_types.ts, core/js/typespecs/app_types.ts, core/js/typespecs/common_types.ts, core/js/typespecs/openai/messages.ts, core/js/typespecs/openai/tools.ts, core/js/typespecs/prompt.ts, core/js/typespecs/view.ts
We've decided that by default, our zod object schemas should be in `strip` mode rather than `strict` mode, because there are many usage sites which only want to use the schema for validation, which may not be always up-to-date with the latest schema definition (e.g. the API server, sdk libraries). So `strip` is safer for validation.
For users who do want to check no extra fields, we introduce a `parseNoStrip` utility function which parses the object and checks that no fields were removed from the final object.
=> Replace all usages of `strictObject` with `object`.

js/src/logger.ts
It should also throw if you attempt to cast a logger with `asyncFlush: false` when `logger.asyncFlush === true`.
=> Fix bug in castLogger.

core/js/src/zod_util.test.ts, core/js/src/zod_util.ts
So we can share it with the user.
=> Better error message for parseNoStrip.

js/CHANGELOG.md, js/package.json
The update to the package.json file allow the npm package to link to the repository and the homepage from the main npm page https://www.npmjs.com/package/braintrust
=> Update links for npm package

core/js/typespecs/app_types.ts
Even though we should generally be able to get the org_id from the API key, it might sometimes be necessary to explicitly disambiguate. It's also useful for people to specify an organization to explicitly assert that's the one they're modifying.
=> Add org_id/org_name to patch org members schema.

core/js/typespecs/app_types.ts, core/js/typespecs/common_types.ts, core/js/typespecs/functions.ts, core/js/typespecs/openai/messages.ts, core/js/typespecs/prompt.ts
It seems they require each union item to have a name that they can use for naming the various types.
=> Minor typespecs adjustments for stainless

core/js/typespecs/api_types.ts
This can arise in general when various parts of the application fill in `span_id = root_span_id = id`, and the user is using a manually-provided id. Since these coercions should only occur for non-trace rows, a strong uniqueness constraint is not required anyways.
=> Allow span_id and root_span_id to be non-UUID.

core/js/typespecs/openai/messages.ts, js/src/framework.ts, js/src/logger.ts, py/src/braintrust/framework.py
Mark the entire eval row as failed if the task fails. This makes it easier to filter down to failing rows.
=> Log errors in `Eval()` at the top level

js/src/framework.ts, py/src/braintrust/framework.py
Thread the `baseExperimentName` and `baseExperimentId` options, which are already implemented for `init()`, through to `Eval()`
=> Add base experiment option to Eval

core/js/typespecs/api_types.ts
People should be using `/btql` instead.
=> Deprecate fetch filters param

js/src/logger.ts
This function is invoked when lazily initializing the logger object's metadata, either when initializing a logger or when logging to a parent span that originates from a logger. In the former case, we were already logging in with the user's provided params, but in the second case, we still need to log in.
This matches the implementation in the python `logger.py`, so it was just an accidental omission.
=> Fix bug in `computeLoggerMetadata`

py/src/braintrust/logger.py
To get correct signatures for default implementations of the context manager methods.
=> Use `context.AbstractContextManager` base class

core/js/typespecs/app_types.ts
This lets people invite somebody to multiple groups. They can be IDs or names.
=> Org membership endpoint accept multiple groups.

core/js/src/index.ts, core/js/src/span_identifier_v3.ts, js/src/logger.ts, py/src/braintrust/logger.py, py/src/braintrust/span_identifier_v3.py
We need to support adding arbitrary properties. So basically now the serialized object representation consists of (1) a few required fields (2) a set of fields we can serialize as compressed UUIDs (3) a JSON object for any remaining fields. Hopefully this is extensible enough to avoid further revisions.
Tested out that the slug size is roughly the same as before.
=> Revise span components slug again

core/js/typespecs/api_types.ts
Sometimes we want to log a row (or a trace) where we explicitly exclude it from async scoring. This is not easy to do right now, because you'd have to pass `SKIP_ASYNC_SCORING: true` every time you do any incremental logging. But now we can override the state to disabled once at the beginning and leave it.
=> Add explicit "disabled" state for async scoring.

core/js/src/span_identifier_v3.ts, core/js/typespecs/functions.ts, js/src/logger.ts, py/src/braintrust/logger.py, py/src/braintrust/span_identifier_v3.py
This allows someone to include a set of properties in a span which are propagated to all of its sub-spans. We include this data in the exported span slug, so that it works with distributed tracing too.
=> Support propagated event data in the logging SDK.

py/src/braintrust/logger.py
Before, we would still return `None` when the override logger was reset to `None`.
=> Fix logger override for unit tests.

py/src/braintrust/logger.py
Reverts braintrustdata/braintrust-sdk#371
=> Revert "`Prompt.build` should only render `tools` when non-empty."

py/src/braintrust/logger.py
The existing behavior outputs `"tools": None` when there are no tools, which is not supported by the OpenAI API. Now it will not be rendered.
Re-land #371.
=> `Prompt.build` should only render `tools` when non-empty.

py/src/braintrust/cli/__main__.py, py/src/braintrust/cli/eval.py, py/src/braintrust/framework.py
Previously, the verbose flag was used for both DEBUG log level and printing full stack traces. Now it will only control printing full stack traces.
To see DEBUG logs, pass the `--verbose` flag twice.
=> Python `--verbose` flag maps to INFO log level.

js/src/logger.ts
`initLogger` passes in login params which include `fetch: undefined` and they clobbered `this.loginParams`.
=> Fix global setFetch

core/js/typespecs/api_types.ts, core/js/typespecs/app_types.ts
Query params are passed in as strings, so we need zod to coerce them to the correct type before validating.
=> Coerce non-string query param schemas

core/js/typespecs/api_types.ts, core/js/typespecs/app_types.ts, core/js/typespecs/function_id.ts, core/js/typespecs/functions.ts, core/js/typespecs/openai/messages.ts, core/js/typespecs/prompt.ts
This helps reduce redundancy in the openapi spec.
=> Extract more typespecs into openapi schemas.

py/src/braintrust/framework.py, py/src/braintrust/wrappers/langchain.py
- Import `Iterable` from `typing` instead of `collections`, enabling `Iterator[T]` syntax.
- Replace pipe `|` with `Union` in langchain.py.
=> Improve Python 3.8 type compatibility.

js/src/functions/infer-source.ts
Fixes #390. Seems like dynamically requiring just works ™️
=> Require rather than es module import typescript

core/js/typespecs/prompt.ts
I noticed these while combing through some OTEL attributes and figured we could include these options since they're available in the OpenAI request types.
=> Additional tool choice and response format options

core/js/typespecs/api_types.ts
See explanation in comments. We explicitly write out the non-numerical legacy metrics that we populated to avoid failing validation on those.
=> Change metrics catchall type to numeric.

core/js/src/merge_row_batch.ts, core/js/typespecs/api_types.ts, py/src/braintrust/merge_row_batch.py
The serialized_span_slugs output gives consumers parent span slugs that they can use to attach traces underneath.
When merging across rows with the same (object_id, row_id), we should preserve the original value of certain system fields, instead of using the merged version. This preserves the behavior we would have if we inserted those rows in separate batches.
=> Add serialized_span_slugs to insert output. Fix mergeRowBatch.

core/js/typespecs/prompt.ts
Reverts braintrustdata/braintrust-sdk#438
=> Revert "ensure choice_scores nonempty in prompt data schema"

py/src/braintrust/framework.py
Also remove the stack trace and make it clear that this is a performance recommendation, not a requirement.
Fixes #450.
=> Python: Remove `Eval` in async context warning in CLI.

core/js/typespecs/app_types.ts
so that it can be used from PATCH /v1/organization/members
to retrieve the corresponding object cache entry
and populate the audit headers.
=> return org id from /api/organization/members

js/src/wrappers/ai-sdk.ts
We weren't logging the model name, which prevented cost metrics from showing up.
=> Log model in AI SDK

core/js/typespecs/api_types.ts, js/src/logger.ts, py/src/braintrust/logger.py
- Remove the "path lookup"-type filter in the fetch endpoint. For any nontrivial queries, users should just use the `/btql` endpoint.
- Add `tags` to the feedback endpoint.
- Clarify that `metadata` in the feedback endpoint refers to audit metadata, not normal event metadata.
=> A few cleanups to the REST API

py/src/braintrust/functions/invoke.py
By checking the value of `.content`, we were blocking the response on consuming the whole stream.
=> Fix streaming in python

py/src/braintrust/framework.py, py/src/braintrust/logger.py
1. Split `_EvalCaseDict` to work around an issue where Pylance still tries to check the type of an unspecified but `NotRequired` field of a `TypedDict`.
1. Explicitly allow `_ExperimentDatasetEvent` so the type checker does not have to check compatibility between `_ExperimentDatasetEvent` and `_EvalCaseDict`.
=> Python: Improve `EvalData` type annotation.

js/src/cli.ts, js/src/framework.ts, py/src/braintrust/cli/eval.py, py/src/braintrust/framework.py
The two ways of initializing experiments (directly through `Eval()` and through `braintrust eval`) have gotten out of sync. There's likely a better consolidation we can do here, but as a first step, I sync'd them back up and added a comment describing that we should keep them in sync
=> Fix init args between cli/framework

js/package.json, js/src/framework.test.ts, js/src/framework.ts, py/src/braintrust/framework.py
- Introduces new `hooks.metadata` (a reference to the metadata for the eval)
- Deprecates existing `hooks.meta` in favor of metadata
- Improves existing framework tests
This change provides a way for developers to read metadata and allows them a chance to mutate it without calling a function. 
- Updated framework tests to verify new metadata functionality
- Verified backward compatibility with existing `hooks.meta` usage
=> [BRA-1834] feat: Add hooks.metadata and deprecate hooks.meta

py/src/braintrust/_types.py
datamodel-codegen generates its output according to the directory's
configured formatter.
We now always generate it in a temporary directory without
any configured formatter,
and format it with pre-commit.
Since our formatter is not completely normative, we have this one diff.
=> formatting quirk

py/src/braintrust/__init__.py, py/src/braintrust/audit.py
and provide a utility function in the python SDK to parse it
=> compress audit resources header with gzip

js/src/logger.ts, js/src/prompt-cache/prompt-cache.test.ts, js/src/prompt-cache/prompt-cache.ts
to take the memory cache directly,
as we do the disk cache.
=> refactor prompt cache constructor

js/src/logger.ts
In the case where we don't have to produce summary metrics, there's no reason to flush
=> Don't flush until we request experiment summary metrics

js/src/cli.ts, js/src/framework.ts, js/src/logger.ts
Because we bundle when we run `npx braintrust eval`, `instanceof Dataset` will return false (since it's technically a different symbol in the bundled JS).
Instead, we perform a specific check to see if it's our Dataset class, and if so, trick typescript into thinking so.
=> Fix init dataset in `npx braintrust eval`

py/src/braintrust/logger.py
remove the overload; there are no other ones.
=> fix pyright for traced

py/src/braintrust/cli/install/api.py, py/src/braintrust/cli/install/logs.py
`braintrust install api my-stack --create --org-name myorg --enable-brainstore true --brainstore-instance-key-pair-name my-keypair --brainstore-license-key "brainstore-xyz..."`
Full list of CLI args:
```
--enable-brainstore {None,true,false}
Enable Brainstore object-storage data backend
--brainstore-license-key BRAINSTORE_LICENSE_KEY
The license key to use for Brainstore
--brainstore-instance-key-pair-name BRAINSTORE_INSTANCE_KEY_PAIR_NAME
The EC2 Key Pair to allow SSH access to the Brainstore instance
--brainstore-instance-type BRAINSTORE_INSTANCE_TYPE
EC2 instance type for Brainstore. Must be a Graviton instance type.
--brainstore-instance-count BRAINSTORE_INSTANCE_COUNT
Number of Brainstore instances to run
--brainstore-max-instance-count BRAINSTORE_MAX_INSTANCE_COUNT
Max scaling size …
```
=> Add support for Brainstore in the CLI

core/js/src/object.ts, core/js/typespecs/api_types.ts
We don't recommend using this field due to possibility of race conditions when tracing, and will no longer support it in future versions of braintrust.
=> Deprecate `_parent_id` field for tracing.

js/src/stackutil.ts
We have seen intermittent issues where trace.split seems to be running on something that is not a string. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/stack seems to indicate that the behavior may not be consistent. This is an attempt to address that.
=> Account for weird types that are returned by error.stack

js/src/framework.ts, py/src/braintrust/framework.py
We historically fail the whole eval case when a scorer fails. But now that we can report errors more granularly (per scorer), we don't really need to do this.
We still print the error to the terminal, but now let just the individual scorer fail. 
In the UI, it looks like this:
=> Print but do not fail when scorers fail

js/src/logger.ts, js/src/util.ts, py/src/braintrust/__init__.py, py/src/braintrust/logger.py
This way it will pick up any initialization-time environment variable settings the first time it is used, rather than when the module is first imported.
=> Initialize global background logger lazily.

js/src/logger.test.ts, js/src/logger.ts, py/src/braintrust/logger.py, py/src/braintrust/test_logger.py
Ensure `permalink` doesnt throw errors with `NoopSpan`s.
=> Fix noop permalink

.github/workflows/py.yaml, Makefile, py/noxfile.py, py/setup.py
Nox is used for scriptable testing. We're using it to test against multiple versions of the anthropic library and most importantly always the latest version of the library so we'll catch any updates that we don't play nicely with.
=> Add nox tests.

.github/workflows/py.yaml, py/noxfile.py, py/setup.py, py/src/braintrust/wrappers/anthropic.py
- `wrap_anthropic` would fail if anthropic wasn't installed
-  fixed the nox tests (which weren't quite running properly)
- added some tests to ensure our library can always be imported and run core tests without extra dependencies
=> anthropic: ensure the library runs without anthropic

py/src/braintrust/wrappers/openai.py
**Issue**:
When using the OpenRouter API, token usage data only includes the keys input_tokens and output_tokens, rather than the standard OpenAI keys (prompt_tokens, completion_tokens, total_tokens). This mismatch resulted in KeyError exceptions in the Braintrust tracing implementation.
code snippet:
```python
from agents import Agent, Runner, AsyncOpenAI, OpenAIChatCompletionsModel, set_trace_processors
from braintrust import init_logger
from braintrust.wrappers.openai import BraintrustTracingProcessor
from src.config import settings
openai_provider = AsyncOpenAI(
api_key=settings.OPENROUTER_API_KEY,
base_url=settings.OPENROUTER_BASE_URL,
)
tool_model = OpenAIChatCompletionsModel(
openai_client=openai_provider,
model="google/gemini-2.0-flash-lite-preview-02-05:free"
)
tool_agent = …
```
=> Fix: faulty token count dict lookup in openai-agents wrapper for python sdk

py/src/braintrust/oai.py
Running `LLMClassifier` eval in Python produces the following traceback on `openai==1.65.2` for me.
```
Traceback (most recent call last):
File "/Users/.../agent-backend/classifier.py", line 32, in <module>
result = classifier.eval(output="""
File "/Users/.../agent-backend/.venv/lib/python3.10/site-packages/braintrust_core/score.py", line 47, in eval
return self._run_eval_sync(output, expected, **kwargs)
File "/Users/.../agent-backend/.venv/lib/python3.10/site-packages/autoevals/llm.py", line 261, in _run_eval_sync
return self._postprocess_response(run_cached_request(**self._request_args(output, expected, **kwargs)))
File "/Users/.../agent-backend/.venv/lib/python3.10/site-packages/autoevals/oai.py", line 383, in run_cached_request
wrapper = prepare_openai(client=client, is_async=False, …
```
=> Add an attribute check for `responses` in OpenAI 

js/src/wrappers/ai-sdk.ts
The AI SDK wrapper function `wrapAISDKModel` is setting `time_to_first_token` again after finishing the stream, causing wrong metrics in the dashboard.
This PR sends the correct one (the one set on first token).
=> fix(ai-sdk): do not set time_to_first_token to the latest token

core/js/typespecs/functions.ts
ref braintrustdata/braintrust#4939
Generating stop token on client is more flexible for more granular stopping semantics when stopping columns, cells, etc
=> Pass stop token to run from client

js/src/logger.ts
this is used to configure the http logger in end-to-end tests
=> add state.httpLogger()

js/src/logger.test.ts, js/src/logger.ts
Improvement to playground serverside-stop which drops logs once the eval is aborted
=> add ability to disable logging for aborted runs

CODEOWNERS, core/js/src/object.ts, js/src/logger.ts, py/src/braintrust/logger.py, py/src/braintrust/object.py
Data planes have supported the `/logs3` endpoint for long-enough that we don't expect users of new SDKs to rely on this fallback. The fallback essentially doubles the number of retries against the data plane from 3 to 6, so this will also bring that down to 3. We can consider re-bumping that if necessary.
=> Remove fallback to legacy `/logs` endpoint when logging

py/src/braintrust/framework.py
We were incorrectly treating `*args` as a named argument, when we really should be ignoring it.
=> Fix positional arg in scorer

js/src/cli.ts, js/src/framework.ts, py/src/braintrust/cli/eval.py, py/src/braintrust/framework.py
We've supported this forever but just didn't propagate it through `Eval(...)`
=> Allow propagating description and summarize_scores

js/src/functions/stream.ts
Streams can't fail. Propagating an error, rather than throwing an exception, allows us to surface it on the other end of the stream properly.
=> Propagate error rather than exception

js/src/wrappers/oai.test.ts
move test suite options to second param. last param is deprecated
https://github.com/vitest-dev/vitest/issues/5121
this is mostly a whitespace change
=> vitest now wants test options as the 2nd param

js/src/browser-config.ts, js/src/isomorph.ts, js/src/node.ts, js/src/prompt-cache/disk-cache.test.ts, js/src/prompt-cache/disk-cache.ts, js/src/prompt-cache/prompt-cache.test.ts, py/src/braintrust/prompt_cache/disk_cache.py, py/src/braintrust/prompt_cache/test_disk_cache.py, py/src/braintrust/prompt_cache/test_prompt_cache.py
- hash keys for safe filesystem access
- never throw errors into the app because of filesystem errors.
=> Solidify prompt cache.

.github/workflows/py.yaml, .gitignore, py/noxfile.py, py/src/braintrust/oai.py, py/src/braintrust/wrappers/test_openai.py, py/src/braintrust/wrappers/test_pydantic_ai.py, py/src/braintrust/wrappers/test_utils.py, pyproject.toml
- properly wrap some async responses  Fixes #680 
- add a bunch of tests to better exercise the openai API
- the tests found a bug where some metrics were missing 
- fix some pydantic warnings `Deprecation warning in Pydantic. The method "dict" in class "BaseModel" is deprecated.` Try `model_dump` and fallback to `dict`
- set an asyncio loop scope (fixes a warning message in tests)
=> Properly wrap async openai pydantic responses

js/examples/anthropic_beta_example.ts, js/examples/anthropic_example.ts, js/src/wrappers/anthropic.test.ts, js/src/wrappers/anthropic.ts
wrap `anthropic.beta.messages` requests. It has the same api, so we can use the same mechanism as `anthropic.messages` (for now). Added a bunch of tests also. 
This addresses #BRA-2387.
=> anthropic.ts: trace messages.beta.create|stream

py/noxfile.py, py/setup.py, py/src/braintrust/framework.py, py/src/braintrust/git_fields.py, py/src/braintrust/logger.py, py/src/braintrust/prompt.py, py/src/braintrust/score.py, py/src/braintrust/serializable_data_class.py, py/src/braintrust/test_framework.py, py/src/braintrust/test_serializable_data_class.py
This simplifies our deployment and ensures our users can't end up in dependency well between `braintrust_core`, `braintrust` and `autoevals`. 
- copy `serialized dataclass` since it's a util
- duck-type of `Score` and `Scorer` objects rather than checking `isinstance`
- add tests for both classes and runs them with and without braintrust core and autoevals installed.
=> Remove dependency on `braintrust_core`

js/src/cli-util/pull.ts, js/src/framework2.ts
This makes the "Try prompt" experience fully rich and accurate.
=> Populate a prompt's id, version, and project_id in `braintrust pull`

py/src/braintrust/gitutil.py
The `is_dirty` function can also fail if git fails for some arbitrary reason. This was showing up in some of our internal CI tests.
=> gitutil: be more robust to git execution errors

core/js/typespecs/functions.ts, js/examples/anthropic_tools_example.ts, js/src/functions/invoke.ts, js/src/logger.test.ts, js/src/logger.ts, js/src/prompt-cache/disk-cache.test.ts, js/src/prompt-cache/disk-cache.ts, js/src/wrappers/oai.test.ts, py/src/braintrust/functions/invoke.py
To make it easier to add tags/metadata to the logged spans for `invoke`.
Also fixed a bunch of typescript errors that were blocking docs updates.
=> Propagate tags and metadata to invoke

core/js/typespecs/view.ts
Adding a new type that can be used for saving monitoring page views. Shooting for backwards compatibility.
Also bringing this in line with https://github.com/braintrustdata/braintrust/pull/5907
=> update view to match new DB schema

.github/workflows/js.yaml, Makefile, js/Makefile, js/package.json, js/src/functions/upload.ts, js/src/wrappers/anthropic.test.ts, js/tsconfig.json, js/typedoc.json, pnpm-lock.yaml
- this `typedoc` in the JS build so we'll get alerted when we break it. it doesn't do anything with it though. 
- updates typedoc and markdown plugins based on @ibolmo's work in #690
- skips tests and examples 
- adds `prettier` as a dev dependency so we can find the imports in the cli module.
- fixes some minor broken type issues
=> Fix JS docs build

core/js/typespecs/view.ts
- Add groupBy as optional string field to monitorViewOptionsSchema
- Enables saving and loading groupBy selections with monitor views
=> Add groupBy field to monitor view options schema

integrations/langchain-py/noxfile.py, py/Makefile
speeds up our windows CI (which is the blocker) by about 25% .
build (3.13, windows-latest)  before:6m 7s  -> 4m 27s  
build (3.13, ubuntu-latest)   before:3m 1s  -> 2m 30s
=> use uv in langchain tests

js/Makefile, js/package.json, js/src/logger.ts, js/src/queue.bench.ts, js/src/queue.test.ts, js/src/queue.ts, pnpm-lock.yaml, py/src/braintrust/logger.py, py/src/braintrust/queue.py, py/src/braintrust/test_queue.py
Change our SDK queue behaviour such that:
- by default we drop logs if our size is > X 
- the current default is 5000, which is up for discussion. 
- by default we drop oldest logs if it's full
- this means in python we drop the `BRAINTRUST_QUEUE_DROP_WHEN_FULL` env variable, since it will always do this.
- also splits the queue up so we can unit test easier
- uses deques for efficient dropping when full 
- don't allow unlimited queue sizes anymore 
The user impact is that (a) we coarsely bound our memory use ... albeit without a ton of control (b) we never block application threads when full. I think both of these are good traits and users will understand them
JS and Python have diff env variables for the queue size (`BRAINTRUST_QUEUE_SIZE`, `BRAINTRUST_QUEUE_DROP_EXCEEDING_MAXSIZE`) . …
=> make the queue non-blocking by default 

py/src/braintrust/logger.py, py/src/braintrust/test_logger.py
See this issue here: https://discord.com/channels/1146930518722609238/1389049635515011082/1389049635515011082
If using `@traced` without parenthesis you get the linting error below.  This PR fixes it.
=> Fixes linting issue with @traced when used without parenthis

js/src/gitutil.ts, py/src/braintrust/gitutil.py
Per chat with @ankrgyl, increasing `get_past_n_ancestors()`'s default `n` value. This helps when you don't run evals on every commit on the baseline branch (master), but only some of them, which may be more than 10 commits in the past. This is what we do, as only some commits to PostHog touch AI features. In that case currently the comparison just gets borked.
This is a major increase on the limit, by a factor of 100 – however from quick performance testing, there is zero meaningful performance difference. Git seems incredibly fast at this. The test:
```python
import timeit
execution_time = timeit.timeit('get_past_n_ancestors(n=1000)', globals=globals(), number=1000)
print(f"Average execution time over 1000 runs: {execution_time:.6f} seconds")
```
The output:
```
Average execution time …
```
=> Increase get_past_n_ancestors default to 1000

py/scripts/validate-release-tag.sh
A release tag can be deleted and re-applied and sometimes cached on github actions.
=> allow release tags to be deleted / re-applied

py/src/braintrust/cli/install/api.py
This is no longer the recommended self-hosting method so I didn't catch this earlier
=> set PrimaryOrgName parameter in cloudformation template

js/examples/otel/custom_otel_example.ts, js/src/otel.test.ts, js/src/otel.ts, py/src/braintrust/otel.py, py/src/braintrust/test_otel.py
there are some `traceloop.*` spans we want to keep for context in our AI Span Processor.
=> keep traceloop.* spans

core/js/typespecs/app_types.ts
Reverts braintrustdata/braintrust-sdk#549 -- prematurely merged before other PR was ready to go
=> Revert "Custom column type update - BRA-1935"

integrations/openai-agents-js/package.json, py/src/braintrust/version.py
This fixes an openai-agents bug where the tracing context didn't get inherited.
=> Bump versions braintrust (py) v0.2.3 and openai-agents (js) v0.0.2

core/js/typespecs/prompt.ts
So that our internal generator doesn't bundle the `z.null()` union variant into the main `responseFormatSchema`.
=> Adjust typespec

js/src/framework.test.ts, js/src/framework.ts, js/src/logger.ts, py/src/braintrust/framework.py, py/src/braintrust/test_framework.py, py/src/braintrust/test_helpers.py
adding support for tags allows filtering eval logs by an array of strings
ref: https://www.braintrust.dev/docs/reference/libs/python#evalhooks-objects
=> Add support for tags when using eval hooks

js/src/isomorph.ts, js/src/logger.test.ts, js/src/logger.ts, js/src/node.ts, py/src/braintrust/logger.py, py/src/braintrust/test_logger.py
Previously, filepath-based attachments weren't validated until the logger was flushed, which caused missing or unreadable files to fail silently. 
This PR introduces a synchronous check upon attachment creation to raise non-existent file issues earlier.
=> validate file readability when creating attachments

js/src/wrappers/oai.test.ts, js/src/wrappers/oai_responses.ts
This looks worse until we clean it up in the UI but is strictly better due to not hiding any data.
=> Switch responses wrapper for js to not do transforms (similar to the agents wrapper)

core/js/src/generated_types.ts, core/js/src/object.ts, core/js/src/span_identifier_v1.ts, core/js/src/span_identifier_v2.ts, core/js/src/span_identifier_v3.ts, core/js/src/zod_util.test.ts, core/js/src/zod_util.ts, integrations/langchain-js/package.json, integrations/langchain-js/src/BraintrustCallbackHandler.test.ts, integrations/openai-agents-js/src/openai-agents-integration.test.ts, integrations/val.town/src/commands/update.ts, js/btql/ast.ts, js/dev/errorHandler.ts, js/dev/server.ts, js/dev/types.ts, js/examples/dev-server.ts, js/examples/otel/aisdk_example.ts, js/examples/otel/package-lock.json, js/examples/wrappers/ai-sdk-v1.ts, js/scripts/openapi_zod_client_output_template.hbs, js/src/cli-util/pull.ts, js/src/eval-parameters.ts, js/src/framework-types.ts, js/src/framework2.ts, js/src/functions/invoke.ts, js/src/functions/stream.ts, js/src/functions/upload.ts, js/src/generated_types.ts, js/src/parameters.test.ts, pnpm-lock.yaml
This change updates the imports for zod from `import { z } from "zod";` to `import { z } from "zod/v3";` to improve support for zod v4 in the SDK.
My application is using zod v4 (`^4.0.15` specifically) which causes issues when building a prompt via the Braintrust SDK. In my code, I load a prompt and then attempt to build it:
```ts
const prompt = await loadPrompt({ projectId: "my-project-id", slug: "my-prompt-slug" });
const built = prompt.build({ some: "params" });
```
This results in an error on the `prompt.build` line:
```
TypeError: Cannot read properties of undefined (reading '_zod')
at t._zod.parse (/my-code/index.js:3671:6503)
at /my-code/index.js:3654:655
at t.safeParse (/my-code/index.js:3673:4749)
at Fen.runBuild (/my-code/index.js:3763:12868)
at Fen.build …
```
=> Improve support for zod v4

js/src/logger.test.ts, js/src/logger.ts
Fixes: https://github.com/braintrustdata/braintrust-sdk/issues/912
=> avoid logging BT API keys when logging Span objects

integrations/langchain-js/package.json, pnpm-lock.yaml
This was very subtle. When we published 0.0.6 langchain-js integration the existing braintrust version was 0.0.160 (as [seen in npmjs](https://www.npmjs.com/package/@braintrust/langchain-js?activeTab=code)). When we moved from 0.0.x to 0.x.y (actual SEMVER) we neglected to publish a new langchain-js that had the latest minor version. This is important since we had shipped various fixes to tracing context propagation.
=> Fix langchain-js to require min ^0.3.7

integrations/openai-agents-js/package.json, integrations/openai-agents-js/src/openai-agents-types.ts, integrations/openai-agents-js/src/types.ts, pnpm-lock.yaml
I don't think these were actually doing anything and us depending on these libraries would cause them to go out of sync sometimes (since they also depend on each other) and cause lots of issues. This is much easier. 
Tested locally with npm link.
=> Get rid of peer dependencies that we don't need. 

integrations/langchain-js/package.json, pnpm-lock.yaml
we recently bumped braintrust minor version which causes a ripple of dependency problems. previously things just worked because we were still on 0.3.x but that was hiding the problem. 
the move to peer dependency is a breaking change. thus, we do need to bump from 0.0.x to minor. we will now require folks to directly depend on the braintrust library. 
with this approach we should be using the exact `currentSpan` (should be just one copy of braintrust), so this will also settle those surprises.
=> BRA-2992 move langchain-js braintrust dep to peer
