braintrustdata/braintrust-sdk

js/src/logger.ts, py/src/braintrust/logger.py
It can be confusing to users if they change some of their login information, that running login/init/whatever doesn't actually log them in again, unless they explicitly specify force_login.
Tested: I can remove `force_login=True` in the braintrust internal unittests, which use the SDK to create a new org for each test.
Fixes BRA-403
=> SDK: Force login if input parameters change.

py/src/braintrust/logger.py
This was confusing, more than helpful.
=> Remove project link in python

js/src/logger.ts, py/src/braintrust/logger.py
This both reduces a roundtrip and also keeps the logger alive if `ping()` fails.
We still need to make the logger return a no-op object if it cannot connect to braintrust at all.
Fixes BRA-527
=> Remove ping from the logger

py/src/braintrust/framework.py
* Restore scoring functions' ability to return simple (non-`Score`) values
=> Small fixes while writing docs

js/src/logger.ts, py/src/braintrust/logger.py
- Before, we would crash when a user tried logging something to metrics in the initial log statement, e.g. `experiment.log(metrics={"foo": 1}, ...)`. This is because the SDK would already be trying to log to metrics internally through `self.initial_data`, and the keys would conflict with the user trying to log to metrics in their event. We address this by deep-merging the user's data into `self.internal_data` before logging.
- Users want to be able to override the automatically-populated "start"/"end" times in a span. We just remove the checks that forbid this, so they can override any of the metrics.
=> Fix logging issues around metrics.

py/src/braintrust/logger.py
=> Fix race condition when logging from multiple threads.

js/src/logger.ts, py/src/braintrust/logger.py
It requires updating tests, so we did it in a separate PR from https://github.com/braintrustdata/braintrust-sdk/pull/45.
=> Address TODO

js/src/logger.ts, py/src/braintrust/logger.py
* Validate that metrics are shallow dicts (one level deep, values are numbers).
=> Properly validate that logged metrics are shallow dicts

js/src/gitutil.ts
* Try to match common branch names (`main`, `master`, `develop`) before resorting to a full `git remote show` to find the base branch.
This change mostly copies the existing logic in `gitutil.py`.
Fixes BRA-677.
=> Implement `COMMON_BASE_BRANCHES` in JS to speed up common branch lookup

py/src/braintrust/cli/install/api.py
These options are no longer used by the lambda API.
=> Remove unnecessary configuration params.

js/src/framework.ts, py/src/braintrust/framework.py
Now that we support visualizing trials in the product, this change makes them really easy to run in the eval framework.
=> Add support for trial count parameter

js/package-lock.json, js/package.json
We should find a less manual solution, perhaps using a pnpm workspace.
=> Update braintrust core version.

js/src/cli.ts, js/src/framework.ts, py/src/braintrust/cli/eval.py, py/src/braintrust/framework.py
* Add support for public experiments through `Eval(...)`
* Add support for `--jsonl` flag to make parsing outputs easy (eg in CI)
=> Small improvements to eval framework (jsonl, public experiments)

js/src/logger.ts
Essentially we accomplish this by logging promises instead of materialized objects. The logger resolves all the promises before logging. Intermediate steps share promises, which should just resolve to the same value once they are awaited, so we're basically using them as a "lazily-computed value".
We also make the async part of the Logger API optional by introducing a generic parameter `IsAsyncFlush`. By default, it is false, so all logging operations will flush and are thus async. But if the user passes the argument `asyncFlush: true` (which should cause typescript to infer the type of `IsAsyncFlush` as `true` as long as they provide a literal), it will stop flushing automatically and the type signatures will no longer be wrapped in promises.
=> JS API: Make all data objects lazily-initialized.

js/src/logger.ts, py/src/braintrust/__init__.py, py/src/braintrust/logger.py, py/src/braintrust/util.py
Analogous to https://github.com/braintrustdata/braintrust-sdk/pull/78.
=> Implement lazy-login for python SDK

core/js/src/score.ts, core/py/src/braintrust_core/score.py, js/src/framework.ts, js/src/logger.ts, py/src/braintrust/framework.py, py/src/braintrust/logger.py
=> Fix null scores

core/js/src/index.ts, core/js/src/span_types.ts, core/py/src/braintrust_core/span_types.py, js/src/framework.ts, js/src/logger.ts, js/src/oai.ts, py/src/braintrust/framework.py, py/src/braintrust/logger.py, py/src/braintrust/oai.py
If the `type` attribute is set, we'll now print some useful information in the UI
=> Track span types

js/src/logger.ts, py/src/braintrust/logger.py
So "metrics" can remain numerical.
=> Move caller location info to "context" field.

js/src/framework.ts
Before this change, we were incorrectly reporting the number of datapoints in a trial
=> Flat map before computing number of data points

js/src/logger.ts
Fix the ObjectFetcher iterator.
=> Fix object iterator

py/src/braintrust/logger.py
=> Allow modifying output stream.

core/js/src/git_fields.ts, core/py/src/braintrust_core/git_fields.py, js/src/gitutil.ts, js/src/isomorph.ts, js/src/logger.ts, js/src/node.ts, py/src/braintrust/gitutil.py, py/src/braintrust/logger.py
- Allow creating experiments/projects using project ID (Fixes BRA-820)
- Allow specifying other init parameters explicitly (repo status and base experiment ID). Repo status was explicitly requested.
=> Small enhancements to experiment/dataset creation

js/src/logger.ts
To align with all the other span implementations.
=> Fix noop span signature

.github/workflows/lint.yaml, core/js/src/db_fields.ts, core/js/src/object.ts, core/js/src/typespecs/api_types.ts, core/py/src/braintrust_core/__init__.py, core/py/src/braintrust_core/object.py, core/py/src/braintrust_core/util.py, js/src/framework.ts, js/src/logger.ts, py/src/braintrust/logger.py
=> Add linter check to CI.

js/src/logger.ts, py/src/braintrust/logger.py
=> Raise an exception if trying to log toplevel with an active span.

py/src/braintrust/logger.py
It should be using `_refetch` instead of `_fetched_data`.
=> Fix version property for ObjectFetcher.

core/js/src/typespecs/api_types.ts
It should be minimum, not maximum
=> Fix docs for fetch query pagination.

py/src/braintrust/oai.py
We do this in typescript already.
=> Python OAI wrapper: allow logging root spans.

core/js/src/util.ts, js/src/logger.ts
This change simply factors out the request batching logic so it can be used in more places.
=> Factor out batch update logic

js/src/framework.ts, py/src/braintrust/framework.py
* Update typedefs to support nullable scores in TS and Python
* Support numeric scores in TS and handle nullable scores correctly.
=> Fix nullable and numeric scores

js/src/logger.ts
=> Export dataset type

py/src/braintrust/logger.py
In Typescript, the type assertion should be enough.
=> Do not permit dict tags in python

js/src/oai.ts, py/src/braintrust/oai.py
* We were only returning the first choice from the JS wrapper. This change updates it to include all choices.
* For streaming mode, only log the final output (not each chunk). We aim to make it the same format as the non-streaming output.
=> OpenAI wrapper improvements

py/src/braintrust/framework.py
=> Remove kw_only

js/src/framework.ts, js/src/logger.ts, py/src/braintrust/framework.py, py/src/braintrust/logger.py
Just propagate along the `update` flag to `init`.
=> Support updating an existing experiment

core/js/typespecs/app_types.ts
We need the zod schema for permissions.
=> Align with adding RBAC checks to REST API

core/js/typespecs/app_types.ts
Aligns with an internal change to add object_id filters to the REST API.
=> Include query param for filtering GET request by object IDs.

js/src/cache.ts, py/src/braintrust/cache.py, py/src/braintrust/logger.py
No longer needed.
Fixes BRA-1259.
=> Remove cache utils in SDK.

py/src/braintrust/logger.py
=> Use metric summary instead of score summary

py/src/braintrust/cli/install/api.py
* Properly propagate the `--managed-postgres` argument
* Add a `--postgres-version` param
* Fix logger format string issue.
=> Fix param formatting and add postgres version parameter

core/js/typespecs/api_types.ts, js/src/framework.ts, js/src/logger.ts, py/src/braintrust/framework.py, py/src/braintrust/logger.py
NOTE: This will fail on old stacks (so users ought to update their stacks before running it).
=> Always call the summary endpoint, even if you do not have scores

js/src/index.ts, js/src/isomorph.ts, js/src/logger.ts, js/src/node.ts, js/src/stackutil.ts, py/src/braintrust/logger.py
For debugging. Also fix a few other miscellaneous issues.
Fixes BRA-1264.
=> Add environment variable for writing failed publish payloads to filesystem.

core/js/typespecs/app_types.ts
=> Add schema for prompt session

js/src/framework.ts
The progress reporter messes with TTY settings.
=> Stop progress reporter after running an eval

core/js/src/http_headers.ts, core/py/src/braintrust_core/http_headers.py
Aligns with internal changes to support user impersonation.
=> Add header for user impersonation.

core/js/typespecs/app_types.ts
=> Add org_project RBAC noun.

js/jest.config.js, js/package.json, js/src/framework.test.ts, js/src/framework.ts, pnpm-lock.yaml
Also sets up jest for the SDK dir.
=> fix(sdk-js): timeout evaluation with user-provided timeout

core/js/typespecs/app_types.ts
Aligns with internal change to remove the nouns.
=> Remove project_score and project_tag acl nouns.

js/src/wrappers/oai.ts, py/src/braintrust/oai.py
Tracks https://github.com/braintrustdata/braintrust-proxy/pull/71
=> Use new cache headers

.github/workflows/js.yaml, core/js/package.json, core/js/src/util.test.ts, core/js/vitest.config.js, js/jest.config.js, js/package.json, js/src/framework.test.ts, js/vitest.config.js, package.json, pnpm-lock.yaml
Switch from jest to vitest. Also add a github workflow to run the tests.
=> Setup js tests

core/js/typespecs/app_types.ts, core/js/typespecs/common_types.ts
Aligns with repo-internal PR to add API key management to the REST API.
=> Typespecs for API key management.

py/src/braintrust/framework.py
=> Add max concurrency in Python

js/src/framework.ts
Prior to this, in environments like `tslab`, if the `Eval` is the return value of the cell, it prints the entire result set.
=> Print evals nicely

py/src/braintrust/__init__.py, py/src/braintrust/framework.py, py/src/braintrust/logger.py, py/src/braintrust/util.py
Motivation explained in comments.
=> Add wrapper for marking functions as async.

js/src/index.ts, py/src/braintrust/__init__.py
Improve description for the library, now that Braintrust does more than just logging
=> Tweak library descriptions

js/src/index.ts
This should resolve #353. Please validate before merge.
=> export EvalScorer

core/js/typespecs/app_types.ts, js/package.json, js/src/cli.ts, js/src/functions/infer-source.ts, js/src/functions/load-module.ts, js/src/functions/upload.ts, pnpm-lock.yaml
Small tweaks to improve bundle uploading + data model. Also added logic to read function definition from sourcemaps to populate a preview.
=> Cleanup bundle uploading

core/js/typespecs/app_types.ts
=> Rename score config fields.

core/js/typespecs/api_types.ts, core/js/typespecs/app_types.ts, core/js/typespecs/custom_types.ts, core/js/typespecs/view.ts, js/src/logger.ts
This lets us get replace some type aliasing we missed with zod parsing.
=> Replace 'any' with 'unknown' in typespecs.

js/src/logger.ts, py/src/braintrust/logger.py
Useful for extracting information from a serialized span slug.
=> Export utility function to resolve span components object ID.

py/src/braintrust/logger.py
I introduced this regression in https://github.com/braintrustdata/braintrust-sdk/pull/376
=> Python: Use union type compatible with python3.9 and older.

core/js/typespecs/api_types.ts
- Combine the merge and replacement schemas into one. There's not much point in hard-separating these cases if we don't separate them on the backend. By combining them, somebody now has the ability to log a "merge"-type event which ends up as a replacement because there is no existing row, which is fine.
- Add span_id/root_span_id/span_parents to the insert schema, so that pepole can explicitly specify the trace linkages. This can be useful in other places like attaching function invocations underneath other logged rows.
=> Simplify and generalize event insertion schema.

core/js/typespecs/attachment-reference.ts, js/src/logger.ts, py/setup.py, py/src/braintrust/__init__.py, py/src/braintrust/_types.py, py/src/braintrust/bt_json.py, py/src/braintrust/logger.py, py/src/braintrust/merge_row_batch.py, py/src/braintrust/object.py, py/src/braintrust/prompt.py, py/src/braintrust/types.py, py/src/braintrust/util.py
=> Upload attachments with the Python SDK.

js/package.json, js/src/wrappers/ai-sdk.ts, pnpm-lock.yaml
* New methods for whether or not the model supports images
* Translate the prompt format to openai's
=> Update AI SDK and fix a few issues

core/js/typespecs/api_types.ts, js/src/logger.ts, py/src/braintrust/logger.py
=> Remove dataset record id

py/src/braintrust/cli/push.py
and add argparse choices for if_exists
=> fix pyright for push.py

js/src/logger.ts
Add `render` call to tool_calls array so assistant tools can use input data
=> Add templating to tool_calls array

js/src/logger.ts
Reverts braintrustdata/braintrust-sdk#485
=> Revert "Add templating to tool_calls array"

py/src/braintrust/cli/push.py
=> do not upload a bundle when there are no bundled functions

js/src/logger.ts
Reverts braintrustdata/braintrust-sdk#488
=> Revert "Revert "Add templating to tool_calls array""

py/src/braintrust/logger.py
allows logging nested attachments
=> correctly implement _deep_copy_event in python

py/src/braintrust/logger.py
- **Revert "correctly implement _deep_copy_event in python"**
- **try**
- **more**
- **final**
=> fix _deep_copy_event

integrations/langchain-js/package.json
Fixes: https://github.com/braintrustdata/braintrust-sdk/issues/519
=> Bump version to publish new build

.github/workflows/js.yaml, .github/workflows/py.yaml, core/js/turbo.json, integrations/langchain-js/turbo.json, integrations/vercel-ai-sdk/turbo.json, js/turbo.json, package.json, pnpm-lock.yaml, turbo.json
To align with our internal build upgrades
=> Upgrade turborepo

py/src/braintrust/framework.py
This makes it json serializable
=> Rework DictEvalHooks to actually be a dict

core/js/src/type_util.ts
=> Cleanup type utils signatures

py/src/braintrust/_types.py
Align with https://github.com/braintrustdata/braintrust-sdk/pull/537.
=> Fix python typespecs

integrations/langchain-js/package.json, integrations/langchain-js/src/BraintrustCallbackHandler.test.ts, integrations/langchain-js/src/BraintrustCallbackHandler.ts, integrations/langchain-js/src/setGlobalHandler.test.ts, integrations/langchain-js/src/setGlobalHandler.ts, integrations/langchain-js/src/test/utils.ts
DX improvements from a community request.
=> [BRA-1957] Remove noisy warnings and allow NOOP_SPAN for langchain-js integration

core/js/typespecs/view.ts
Adds playground, tools, and scorers
=> add view types

js/src/functions/upload.ts, js/src/logger.ts, js/src/util.ts, py/src/braintrust/cli/push.py, py/src/braintrust/logger.py, py/src/braintrust/util.py
You need to add a special header
=> Support bundle/attachment uploads to Azure

core/js/typespecs/functions.ts, js/src/logger.ts, py/src/braintrust/logger.py
Things I still need to figure out:
~- [ ] how to pull in btql types into this repo~
~- [ ] python types?~
Any API/interface comments appreciated
=> Allow the objectFetcher to use a btql query for initDataset

core/js/typespecs/common_types.ts, js/src/framework.ts, js/src/logger.ts, py/src/braintrust/_types.py, py/src/braintrust/framework.py
Add created field for datasets into origin
=> Origin created

py/src/braintrust/logger.py
We already retry for error response codes. We should also retry for any sort of networking-related exceptions, like "remote end disconnected".
=> Wrap exceptions thrown by requests in retry logic.

Makefile, core/js/typespecs/attachment-reference.ts, js/src/logger.test.ts, js/src/logger.ts, py/src/braintrust/_types.py, py/src/braintrust/logger.py, py/src/braintrust/test_logger.py
https://linear.app/braintrustdata/issue/BRA-2165/add-support-for-external-bucket-attachments
=> Add support for external bucket attachments

py/src/braintrust/wrappers/openai.py
introduced in this
https://github.com/braintrustdata/braintrust-sdk/pull/599
=> Fix whitespace from contributor commit.

.env.example, Makefile, mise.toml
Adding mise for venv and api keys
=> Adding mise for venv and api keys

core/js/typespecs/app_types.ts, core/js/typespecs/functions.ts
This builds on top of `inline_prompt`
=> add inline functions to invoke

.github/workflows/py.yaml, js/src/wrappers/oai.test.ts, js/src/wrappers/oai_responses.ts, py/noxfile.py, py/src/braintrust/logger.py, py/src/braintrust/oai.py, py/src/braintrust/wrappers/test_anthropic.py, py/src/braintrust/wrappers/test_openai.py
This PR ensures we collect and store the details tokens noted in:
https://platform.openai.com/docs/api-reference/responses/object#responses/object-usage
We were storing them before in typescript, but this PR makes the naming consistent.
=> process openai details tokens

js/src/wrappers/oai.test.ts, js/src/wrappers/oai.ts, js/src/wrappers/oai_responses.ts
=> openai.ts: store detail metrics on chat.completion API

js/src/wrappers/oai.test.ts, py/examples/anthropic_async.py, py/src/braintrust/wrappers/anthropic.py, py/src/braintrust/wrappers/test_anthropic.py
Based on code by @rmann-nflx in #664
=> git anthropic.py:add output when create(stream=true)

.github/workflows/integration-tests.yaml
optionally skip integration tests.
=> add a label to skip integration tests in the SDK repo.

core/js/typespecs/prompt.ts, py/src/braintrust/oai.py
* Add support for pydantic `response_format`
* Add typespecs for `text` response format (in responses api)
=> Handle json schema response format

.github/workflows/publish-py-sdk.yaml
=> install dev deps since we need nox for tests

core/js/typespecs/app_types.ts
https://github.com/braintrustdata/braintrust/pull/5712
=> Org api key management

core/js/typespecs/openai/messages.ts, py/src/braintrust/_types.py
=> Small prompt/model fixes

core/js/typespecs/view.ts
I broke things: https://github.com/braintrustdata/braintrust/pull/5940
This reverts commit d25e73f15b3a94570b0a85e39df20d4f9d6a3ded.
=> Revert "update view to match new DB schema (#720)"

py/Makefile, py/src/braintrust/logger.py, py/src/braintrust/test_helpers.py, py/src/braintrust/test_logger.py, py/src/braintrust/util.py
fixes BRA-1842.
Note, i don't trace the outputs of async generators because the output it's potentially infinite or at least very large.
=> ensure traced works with async generators

js/package.json, py/src/braintrust/version.py
py changeset https://github.com/braintrustdata/braintrust-sdk/compare/py-sdk-v0.1.3...61dc08d380e0b88ed3d5f4651a33ad8ea8e777fa
js changeset https://github.com/braintrustdata/braintrust-sdk/compare/js-sdk-v0.0.205...61dc08d380e0b88ed3d5f4651a33ad8ea8e777fa
=> bump versions

js/src/logger.test.ts, js/src/logger.ts
=> Add span/parent to startSpanArgs

core/js/typespecs/app_types.ts
This reverts commit 75eed65362b1370b90c3a032dac2f366f1469f1f.
=> Revert "Service tokens (#750)"

core/js/typespecs/app_types.ts
This reverts commit f36d187c3fec787dd3d4128001c545de5551bc08.
=> Reapply "Service tokens (#750)" (#780)

core/js/typespecs/openai/messages.ts
Reverts braintrustdata/braintrust-sdk#795
=> Revert "Add developer role to message schema"

core/js/typespecs/openai/messages.ts
Reverts braintrustdata/braintrust-sdk#796
corresponds to https://github.com/braintrustdata/braintrust-openapi/pull/170
=> Revert "Revert "Add developer role to message schema""

core/js/typespecs/api_types.ts, core/js/typespecs/app_types.ts, core/js/typespecs/common_types.ts
Definitions for creating and updating environments.
This is the first step. Second step is to create the endpoints to associate environments with functions, which is broken out this changeset for easier reviewability.
=> Environment endpoint definitions

py/src/braintrust/version.py
Aligns with https://github.com/braintrustdata/braintrust-sdk/pull/808.
=> Bump python SDK version

core/js/typespecs/view.ts
for https://github.com/braintrustdata/braintrust/pull/6816
Also relax the parsing so that we handle backwards compatibility better
=> add median as aggregation enum type

core/js/typespecs/api_types.ts
For internal async scoring purposes
=> Add "force rescore" async scoring control

py/noxfile.py
https://github.com/openai/openai-python/issues/2510
=> skip broken openai latest (1.99.0) version

js/src/framework.test.ts, js/src/framework.ts, py/src/braintrust/framework.py, py/src/braintrust/test_framework.py
=> Add a param to eval that makes the SDK not generate an experiment and log locally

js/package.json, js/src/cli-util/pull.ts
See test prompt: https://www.braintrust.dev/app/braintrustdata.com/p/Olmo/prompts?g=none&tg=false&pr=f2b3f061-131d-4554-8351-f5a7c70d8554
this works:
pnpm dlx braintrust pull --id f2b3f061-131d-4554-8351-f5a7c70d8554
this fails:
npx braintrust pull --id f2b3f061-131d-4554-8351-f5a7c70d8554
=> fix npx braintrust pull for large prompts

integrations/openai-agents-js/package.json, pnpm-lock.yaml
"^" does not work for 0.0.x packages.
=> Fix versioning for oai agents library

py/src/braintrust/version.py
Pulling in the span-in-agent-tool fix
=> New python version release

js/package.json
Minor version jutification: my last change added a lot more to the output that js responses wrapper generates.
=> bump version

integrations/adk-py/README.md, integrations/adk-py/examples/manual.py, integrations/adk-py/examples/manual_eval.py, integrations/adk-py/examples/multi_tool_agent/agent.py, integrations/adk-py/examples/parallel/__init__.py, integrations/adk-py/examples/parallel/agent.py, integrations/adk-py/examples/pyproject.toml, integrations/adk-py/pyproject.toml, integrations/adk-py/src/braintrust_adk/__init__.py, integrations/adk-py/src/tests/test_adk.py
Just a small DX improvement and more forward compatible
=> Google ADK clean the setup_* method

js/src/wrappers/mastra.test.ts, js/src/wrappers/mastra.ts
see: https://github.com/mastra-ai/mastra/pull/8097
ran tests locally -
=> update mastra wrapper methods from `generateVNext`/`streamVNext` to `generate`/`stream`
